# Generated by Django 3.2.8 on 2021-10-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE')], max_length=10)),
                ('year', models.IntegerField()),
                ('usernmae', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('confirm_your_password', models.BooleanField(default=False)),
            ],
        ),
    ]
