# Generated by Django 3.2.8 on 2021-10-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registering',
            old_name='usernmae',
            new_name='username',
        ),
    ]
