# Generated by Django 3.2.8 on 2021-10-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211030_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registering',
            name='branch',
        ),
    ]
