# Generated by Django 3.2.8 on 2021-10-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_registering_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registering',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
