# Generated by Django 3.2.8 on 2021-10-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_registering_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registering',
            name='year',
            field=models.IntegerField(default=2024, max_length=4, null=True),
        ),
    ]
