# Generated by Django 3.2.8 on 2021-11-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211107_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registering',
            new_name='registerings',
        ),
    ]
