# Generated by Django 3.2.8 on 2021-11-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_registerings_registering'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registering',
            new_name='registerings',
        ),
    ]
