# Generated by Django 3.2.8 on 2021-11-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='branch',
            field=models.CharField(max_length=3),
        ),
    ]
