# Generated by Django 3.2.8 on 2021-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211110_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=500)),
                ('upvotes', models.IntegerField(default=0, max_length=1000, null=True)),
                ('downvotes', models.IntegerField(default=0, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
