# Generated by Django 3.2.8 on 2021-11-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211115_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(default='CSE', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=2024, max_length=4, null=True),
        ),
    ]
