# Generated by Django 3.2.8 on 2021-11-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20211115_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=500)),
                ('post_text', models.CharField(max_length=500)),
                ('upvotes', models.IntegerField(default=0, max_length=1000, null=True)),
                ('downvotes', models.IntegerField(default=0, max_length=1000, null=True)),
            ],
        ),
    ]
