# Generated by Django 3.2.8 on 2021-11-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_lession_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linklession',
            old_name='time',
            new_name='time_phase',
        ),
    ]
