# Generated by Django 3.2.8 on 2021-11-16 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_time_linklession_time_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lession',
            name='period_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.linklession'),
        ),
        migrations.AlterField(
            model_name='linklession',
            name='period_no',
            field=models.IntegerField(default=1),
        ),
    ]
