# Generated by Django 3.2.8 on 2021-11-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20211116_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='linklession',
            new_name='linklessions',
        ),
    ]
