# Generated by Django 3.2.8 on 2021-11-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_linklession_linklessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lession',
            name='period_no',
        ),
        migrations.DeleteModel(
            name='linklessions',
        ),
    ]
