# Generated by Django 3.2.8 on 2021-11-16 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20211116_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='linklession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_no', models.IntegerField(default=1)),
                ('time_phase', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='lession',
            name='period_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.linklession'),
        ),
    ]
