# Generated by Django 3.2.8 on 2021-11-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20211116_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linklession',
            name='period_no',
        ),
    ]
