# Generated by Django 3.2.8 on 2021-11-16 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_linklession_period_no'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='post',
        #     name='username',
        # ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
