# Generated by Django 3.2.8 on 2021-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='lession',
            name='branch',
            field=models.CharField(default='CSE', max_length=3),
        ),
        migrations.AddField(
            model_name='lession',
            name='year',
            field=models.IntegerField(default=2024, max_length=4, null=True),
        ),
    ]
