# Generated by Django 3.2.8 on 2021-11-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20211117_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lession',
            new_name='lesson',
        ),
        migrations.RenameModel(
            old_name='linklession',
            new_name='linklesson',
        ),
    ]
