# Generated by Django 3.2.8 on 2021-11-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rename_day_lesson_period_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject_id',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
