# Generated by Django 3.2.8 on 2021-11-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20211118_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
