# Generated by Django 3.2.8 on 2021-11-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_lesson_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
