# Generated by Django 3.2.8 on 2021-11-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_lesson_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=2024, max_length=4),
        ),
    ]
