# Generated by Django 3.2.8 on 2021-11-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='start_time',
        ),
    ]
