# Generated by Django 3.2.8 on 2021-11-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20211119_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_text',
            field=models.CharField(max_length=1000),
        ),
    ]
