# Generated by Django 3.2.8 on 2021-11-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20211119_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='start_time',
        ),
    ]
