# Generated by Django 3.2.8 on 2021-11-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20211122_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppyq',
            name='link',
            field=models.CharField(max_length=3000),
        ),
    ]
