# Generated by Django 3.2.8 on 2021-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_apppyq_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppyq',
            name='qtype',
            field=models.CharField(max_length=10),
        ),
    ]
