# Generated by Django 3.2.8 on 2021-11-26 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20211125_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Conversation Date'),
            preserve_default=False,
        ),
    ]
