# Generated by Django 3.2.8 on 2021-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
