# Generated by Django 3.2.8 on 2021-11-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_post_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
