# Generated by Django 3.2.8 on 2021-11-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='lends',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='lends',
            name='lender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='book',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='author',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='Lends',
        ),
        migrations.DeleteModel(
            name='notification',
        ),
    ]
